go2:
  policy_config_name: "isaaclab48"
  recovery_policy_config_name: "fault_adaptive_180800"
  fault_policy_switch_enabled: true
  fault_alpha_topic: "/robot_joint_controller/fault_alpha"
  gain_alpha_topic: "/rl_sar/gain_alpha"
  foot_contacts_topic: "/rl_sar/foot_contacts"
  fault_alpha_threshold: 0.999
  fault_recovery_blend_time: 1.0
  zero_command_after_fault: true
  dt: 0.005
  decimation: 4
  fixed_kp: [80.0, 80.0, 80.0,
             80.0, 80.0, 80.0,
             80.0, 80.0, 80.0,
             80.0, 80.0, 80.0]
  fixed_kd: [3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0,
             3.0, 3.0, 3.0]
  num_of_dofs: 12
  wheel_indices: []
  torque_limits: [23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5]
  default_dof_pos: [ 0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50,
                     0.00, 0.80, -1.50]
  joint_names: ["FR_hip_joint", "FR_thigh_joint", "FR_calf_joint",
                "FL_hip_joint", "FL_thigh_joint", "FL_calf_joint",
                "RR_hip_joint", "RR_thigh_joint", "RR_calf_joint",
                "RL_hip_joint", "RL_thigh_joint", "RL_calf_joint"]
  joint_controller_names: ["FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
                           "FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller"]
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
